### ISSUE TITLE
UV Coordinates

### ISSUE THREAD

**Issue by ghost** [svip-lab/PlanarReconstruction#11]
Hi. Congratulations for your great achievement with this research!

I was wondering if have any implementation that I could perform to use the plane instance segmentations generated (that represent floors or walls) in the end of Stage I to calculate the UV coordinates and replace it with a different texture like PlaneNet does with Manhattan world assumption.

Would be very interesting to see that kind application implemented in near future with AR.

Best.

**Comment by bertjiazheng** [comment]
Hi @wullish,

We do not predict semantics for each plane instance in our pipeline (same as PlaneNet and PlaneRCNN). For calculating UV coordinates, you can refer to the [code](https://github.com/art-programmer/PlaneNet/blob/88e8c8d7e527ce61620b700babc8232de8804f55/code/utils.py#L4284) by PlaneNet. 

Best,
Jia Zheng

**Comment by ghost** [comment]
Got it, thank you Jia!
