### ISSUE TITLE
Error: No command found to be run.

### ISSUE THREAD

**Issue by GuardianWang** [svip-lab/PlanarReconstruction#13]
Yesterday I ran the code successfully, but today when I tried to run again just now, this error showed up:

(venv) ubuntu2@ubuntu2:~/wzc/projects/PlanarReconstruction$ python predict.py with resume_dir=pretrained.pt input_image=png2/1.png

Usage:
  predict.py [(with UPDATE...)] [options]
  predict.py help [COMMAND]
  predict.py (-h | --help)
  predict.py COMMAND [(with UPDATE...)] [options]
Error: No command found to be run. Specify a command or define main function. Available commands are: print_config, print_dependencies, save_config, print_named_configs, eval

What should I do now? Thanks!

**Comment by bertjiazheng** [comment]
Hi @GuardianWang 

Recently, we rectified the code and remove the commands of _predict.py_. 

If you use the latest version of the code, you can run without any commands: 
 `bash
python predict.py with resume_dir=pretrained.pt
`

If you use the older version, you may need to specify _eval_ command as follows:
`bash
python predict.py eval with resume_dir=pretrained.pt
`

Best,
Jia

**Comment by GuardianWang** [comment]
Adding `eval` between `predict.py` and `with` as follows `python predict.py eval with resume_dir=pretrained.pt input_image=./png2/1.png` worked
