### ISSUE TITLE
How should I specify an image to predict?

### ISSUE THREAD

**Issue by GuardianWang** [svip-lab/PlanarReconstruction#15]
Since the most recent `predict.py` has some modifications, it seems like that I cannnot refer to an image using the original command. Then what should I do? Many thanks!

# Error Info
(planercnn) E:\Users\zichu\PycharmProjects\PlanarReconstruction-master>python predict.py with resume_dir=pretrained.pt input_image=png/1.png
sacred.utils.ConfigAddedError: Added new config entry that is not used anywhere
Conflicting configuration values:
  input_image=png/1.png

**Comment by bertjiazheng** [comment]
It seems that I forget to update command in the README. Please try 
```bash
python predict.py with resume_dir=pretrained.pt image_path=/path/to/image
```
