### ISSUE TITLE
What should val.txt look like?

### ISSUE THREAD

**Issue by GuardianWang** [svip-lab/PlanarReconstruction#16]
There is an error when I try to evaluate the performance of the pretrained model

(planercnn) E:\Users\zichu\PycharmProjects\PlanarReconstruction_old>python main.py eval with dataset.root_dir=png resume_dir=pretrained.pt dataset.bat
ch_size=1
INFO - main - Running command 'eval'
INFO - main - Started run with ID "6"
ERROR - main - Failed after 0:00:02!
Traceback (most recent calls WITHOUT Sacred internals):
  File "C:\Users\zichu\planercnn\lib\site-packages\wrapt\wrappers.py", line 564, in __call__
    args, kwargs)
  File "main.py", line 393, in eval
    data_loader = load_dataset('val', cfg.dataset)
  File "main.py", line 175, in load_dataset
    PlaneDataset(subset=subset, transform=transforms, root_dir=cfg.root_dir),
  File "main.py", line 43, in __init__
    self.data_list = [line.strip() for line in open(self.txt_file, 'r').readlines()]
FileNotFoundError: [Errno 2] No such file or directory: 'png\\val.txt'

**Comment by GuardianWang** [comment]
I found a line to create a `.txt` file in the folder `data_tools`. But what if I want to try the code on my own data? Many thanks!

**Comment by bertjiazheng** [comment]
The txt file contains the file names of training or validation data. 

https://github.com/svip-lab/PlanarReconstruction/blob/ff00f5c438a073cfef6afb46d158003b67c89cf4/data_tools/convert_tfrecords.py#L75

**Comment by bertjiazheng** [comment]
I will close the issue. Feel free to reopen this issue if you have any related questions.

**Comment by GuardianWang** [comment]
> The txt file contains the file names of training or validation data.
> 
> https://github.com/svip-lab/PlanarReconstruction/blob/ff00f5c438a073cfef6afb46d158003b67c89cf4/data_tools/convert_tfrecords.py#L75

That's exactly what I need. Thanks!
