### ISSUE TITLE
Where  is the code for other metrics?

### ISSUE THREAD

**Issue by GuardianWang** [svip-lab/PlanarReconstruction#17]
Hi! I used `main.py` for evaluation and the recall metric would show in my terminal. However, in your paper you also mentioned other metrics, such as VI, SC, RI, etc. Do you have codes for those metrics? Thank you very much!

**Comment by bertjiazheng** [comment]
Please refer to [eval_planes.m](https://github.com/fuy34/planerecover/blob/master/eval/eval_planes.m).

**Comment by GuardianWang** [comment]
Thank you Jiazheng! And I have another question about the count matrix used in [compare_segmentations.m](https://github.com/fuy34/planerecover/blob/master/eval/compare_segmentations.m#L84)


line 79 `segmentcount1=max(max(sampleLabels1)); %class # in seg_1` 
line 80 `segmentcount2=max(max(sampleLabels2)); %class # in seg_2` 
line 84 `n=zeros(segmentcount1,segmentcount2);` 

These lines confued me since in your [main.py](https://github.com/svip-lab/PlanarReconstruction/blob/master/main.py), values in variables `predict_segmentation` and `gt_seg` range from 0 to 20, in which I believe 0 denotes non-planar pixels. So my question is, did you consider about the 0 class, namely those non-planar pixels, when calculating the count matrix and Rand Index? And  an equivalent question is, if there are 21 classes (from 0 to 20) in both prediction and ground truth images, is the shape of your count matrix (20, 20) or (21, 21)?

Thanks. 

@bertjiazheng

**Comment by bertjiazheng** [comment]
Hi,

You need to modify the code to only consider the planar regions.

Best,
Jia

**Comment by GuardianWang** [comment]
And another question is, what should I do when for a coordinate (i, j), a predicted segmentation `S_p`, and a ground truth seg `S_gt`, the following cases happen:
1. `S_p[i, j] == 0, S_gt[i, j] != 0`,
2. `S_p[i, j] != 0, S_gt[i, j] == 0`?

For which element of the count matrix I need to add one? 

Thanks!
@bertjiazheng
