### ISSUE TITLE
How do you define a plane?

### ISSUE THREAD

**Issue by GuardianWang** [svip-lab/PlanarReconstruction#18]
Hi!

I know it seems like a silly question but I believe it's crucial. That's because if we are talking about plane segmentation, we must have a clear idea about what a plane is. However, after seeing some of the labels you used, I have found some inconsistency concerning whether to classify a kind of surface into a plane.

For example, in one image of the test set, the whiteboard and the wall share the same plane label. Nevertheless, in another image, the board and the wall it’s against have different labels.

![b1](https://user-images.githubusercontent.com/31812793/63659834-3c532c00-c7e6-11e9-822c-766a3b59ee29.png)
![b2](https://user-images.githubusercontent.com/31812793/63659833-3c532c00-c7e6-11e9-8ae4-018941f76080.png)

From left to right: original image, prediction, and ground truth.

And could you please tell me what is your initial motivation to concentrate on this area? Is that mainly for 3D reconstruction from 2D images? And do you think the inconsistency in labels have no huge impact on reaching your goal? 

Thank you very much.

**Comment by bertjiazheng** [comment]
Due to the tedious process of manually labelling, PlaneNet employs a multi-model fitting algorithm to automatically extract planes from 3D scans. But such algorithms are sensitive to data noises and outliers, thus introduce inconsistency in the annotations. You can refer to section 4.4 of our paper, where we discuss this inconsistent issue and provide some possible solutions to address these issues.

**Comment by bertjiazheng** [comment]
I think the criterion depends on the application. 

1. If you care about the semantic information. Then you can fit the planes within each semantic instance segmentation. Thus each plane instance only corresponds to a single semantic category. 
2. If you only focus on the geometry and do not care about the semantic, you can merge the nearby plane instances.

You can refer to the [fitting code](https://github.com/art-programmer/PlaneNet/tree/master/data_preparation) provided by PlaneNet. Hope I address your concerns. 

Best,
Jia
