### ISSUE TITLE
some question about Figure of article

### ISSUE THREAD

**Issue by XGuider** [svip-lab/PlanarReconstruction#24]
Thank you for your work. 
Why is the comparison data in the Per plane recall of Figure 9 in this article different from the comparison data in the Per pixel recall of Figure 4 in (PlaneNet)? For example: MWS + GT depth (Per-Pixel), is there any difference between Normal ThresHold and depth ThresHold?

**Comment by bertjiazheng** [comment]
1. Since the PlaneNet does not provide the accurate results of these methods, the results are inferred with the test code of the PlaneNet. 
2. The two results are consistent.
