### ISSUE TITLE
How to calculate FPS please?

### ISSUE THREAD

**Issue by whattheweather** [svip-lab/PlanarReconstruction#26]
Hi,

In the paper, you got 32.26FPS on Titan XP, and which processes were included when you calculated it?

Thanks!

**Comment by niujinshuchong** [comment]
@whattheweather

Forward of the network, clustering, and recovering planar depth were included.

**Comment by whattheweather** [comment]
@niujinshuchong 
Thanks, so I time from             
```
            # forward pass
            logit, embedding, _, _, param = network(image)
```
(https://github.com/svip-lab/PlanarReconstruction/blob/master/main.py#L415)
to
```
            # infer instance depth
            instance_loss, instance_depth, instance_abs_disntace, instance_parameter = \
                instance_parameter_loss(segmentation, sampled_segmentation, sample_param,
                                        valid_region, gt_depth, False)
```
(https://github.com/svip-lab/PlanarReconstruction/blob/master/main.py#L436)
, is that what you mean?

Or should I time until
```
            # mask out non planar region
            predict_segmentation[prob.cpu().numpy().reshape(-1) <= 0.1] = 20
            predict_segmentation = predict_segmentation.reshape(192, 256)
```
(https://github.com/svip-lab/PlanarReconstruction/blob/master/main.py#L459)
?

**Comment by niujinshuchong** [comment]
@whattheweather 
The first one.

**Comment by whattheweather** [comment]
> @whattheweather
> The first one.

Got it! Thanks!
