### ISSUE TITLE
NYUv2 dataset GT generation

### ISSUE THREAD

**Issue by yyangmei** [svip-lab/PlanarReconstruction#27]
Hi,

It seems that there is no NYU's GT generation code in this repo? I find a function named 'fitPlanesNYU' in PlaneNet's repo (https://github.com/art-programmer/PlaneNet/blob/master/utils.py#L1386) 
   , is that what you use? If not, can you release your corresponding code ?

A lot of thanks!

**Comment by niujinshuchong** [comment]
@yyangmei 

The details of GT generation can be found in the paper. 

You can download the generated data from https://drive.google.com/open?id=1WxmpmZzD5TazozizzIVE31jsVgvJAiRu.

**Comment by zhangjingxian1998** [comment]
Dose this data contain each plane's offset? Or just their norm?
