### ISSUE TITLE
_pickle.UnpicklingError: invalid load key, 'v'.

### ISSUE THREAD

**Issue by LeeBY2016** [svip-lab/PlanarReconstruction#28]
When I use predict.py to predict on a single image, I put pretrained.pt under ckpt to the root path and run:
`python predict.py with resume_dir=pretrained.pt image_path=/path/to/image`.
However, there is an error occur:
```
[user@bcm PlanarReconstruction]$ python predict.py with resume_dir=pretrained.pt image_path=ImagePath
WARNING - predict - No observers have been added to this run
INFO - predict - Running command 'predict'
INFO - predict - Started
ERROR - predict - Failed after 0:00:01!
Traceback (most recent calls WITHOUT Sacred internals):
  File "predict.py", line 40, in predict
    model_dict = torch.load(cfg.resume_dir, map_location=lambda storage, loc: storage)
  File "/home/user/anaconda2/envs/plane_embed/lib/python3.6/site-packages/torch/serialization.py", line 358, in load
    return _load(f, map_location, pickle_module)
  File "/home/user/anaconda2/envs/plane_embed/lib/python3.6/site-packages/torch/serialization.py", line 532, in _load
    magic_number = pickle_module.load(f)
_pickle.UnpicklingError: invalid load key, 'v'.

```
Could you give me some advices on what I should do with this error?

**Comment by bertjiazheng** [comment]
Please make sure you download the pre-trained model successfully and give the model path correctly.

**Comment by LeeBY2016** [comment]
> Please make sure you download the pre-trained model successfully and give the model path correctly.

thanks a lot! It is due to the incomplete model donwload.
Considering that I used the 'git clone' command and it tell me download successfully, I think maybe there is something wrong with my git (may need git-lfs)

**Comment by AdityaNikhil** [comment]
@LeeBY2016 Hi there, I want to know if you have fixed your issue. Because, even I'm facing the same issue, I'm trying to deploy an ML app online and the app is successfully deployed but while inferencing, it's showing the same error. 
The model is in my github repo(which I uploaded using git-lfs) and I've clearly mentioned the path to model. I don't know why still it's unable to access the model. Any fixes?!

https://share.streamlit.io/adityanikhil/skyar-online/main/app.py

Open above link and hit Run.

**Comment by pparth195** [comment]
@AdityaNikhil @LeeBY2016 hello,  I also have same error. Please leave a comment if you guys have solved it.

**Comment by ghost** [comment]
+1

**Comment by WeiyeShao** [comment]
I have same error

**Comment by PearlW1** [comment]
+1
I think the model file is destroyed when we download the pre-trained model. but i do not know how tod download the undestroyed pre-trained model.

**Comment by elliestath** [comment]
same error, do we have any news? How can we download the correct pretrained model?

**Comment by AdityaNikhil** [comment]
@elliestath I fixed it by hosting my model on google drive. (You can host on some other platforms as well)
Follow this [answer](https://stackoverflow.com/questions/25010369/wget-curl-large-file-from-google-drive/39225039#39225039) from stackoverflow. 
Let me know if there's anything else.

**Comment by elliestath** [comment]
@AdityaNikhil thanks! I downloaded the model manually and it worked!

**Comment by GitPruthvi** [comment]
@elliestath Hi, I am having same issue. Can you please share how did you download the model manually?

**Comment by niujinshuchong** [comment]
@GitPruthvi 

You can download the model from https://drive.google.com/file/d/1Aa1Jb0CGpiYXKHeTwpXAwcwu_yEqdkte/view?usp=sharing.

**Comment by faridelya** [comment]
![image](https://user-images.githubusercontent.com/60794908/134826682-69a984f0-c730-42ce-a84d-6ba57190196b.png)
hi there i have same issue when deploying on heroku while i have created requirement.txt file as well and the app is running good on local machine but deployment crashed occurred . Please help if somebody know the issue ??

**Comment by David-on-Code** [comment]
I use git instead of https。it's ok.

**Comment by saranyamaity2000** [comment]
> ![image](https://user-images.githubusercontent.com/60794908/134826682-69a984f0-c730-42ce-a84d-6ba57190196b.png) hi there i have same issue when deploying on heroku while i have created requirement.txt file as well and the app is running good on local machine but deployment crashed occurred . Please help if somebody know the issue ??

Same problem I am facing, in local machine it is working fine

**Comment by AnkitKori** [comment]
I am also facing same error please leave a solution if anybody solved.

**Comment by WeiyeShao** [comment]
您好，您的邮件已收到，我会尽快处理并给您回复。邵伟业

**Comment by qiaw99** [comment]
@AdityaNikhil it fixes my problem thank you so much!

**Comment by WeiyeShao** [comment]
您好，您的邮件已收到，我会尽快处理并给您回复。邵伟业

**Comment by jiqibuaixuexi** [comment]
@AdityaNikhil I have tried to download file from google drive, but I get the error : requests.exceptions.ProxyError: HTTPSConnectionPool(host='drive.google.com', port=443): Max retries exceeded with url: /drive/folders/183GHrbNy0Gjx2jJGU25AFIHbciCSJcMN?id=183GHrbNy0Gjx2jJGU25AFIHbciCSJcMN (Caused by ProxyError('Cannot connect to proxy.', OSError(0, 'Error'))).
I need your help to fix the problem, thank you.

**Comment by WeiyeShao** [comment]
您好，您的邮件已收到，我会尽快处理并给您回复。邵伟业

**Comment by Devmuliya16** [comment]
> @AdityaNikhil I have tried to download file from google drive, but I get the error : requests.exceptions.ProxyError: HTTPSConnectionPool(host='drive.google.com', port=443): Max retries exceeded with url: /drive/folders/183GHrbNy0Gjx2jJGU25AFIHbciCSJcMN?id=183GHrbNy0Gjx2jJGU25AFIHbciCSJcMN (Caused by ProxyError('Cannot connect to proxy.', OSError(0, 'Error'))). I need your help to fix the problem, thank you.

you need to enable cors for the host='drive.google.com' to be added as known hosts

**Comment by WeiyeShao** [comment]
您好，您的邮件已收到，我会尽快处理并给您回复。邵伟业

**Comment by C7Y-Richer** [comment]
This post helps me a lot! Thank you very much!!

**Comment by WeiyeShao** [comment]
您好，您的邮件已收到，我会尽快处理并给您回复。邵伟业
