### ISSUE TITLE
Code for implementing Stage II

### ISSUE THREAD

**Issue by JanineCHEN** [svip-lab/PlanarReconstruction#29]
Hi,
Very interesting work. I am wondering if the code also includes the implementation of Stage II, namely the piece-wise planar 3D model mapping? It seems to me that the code only includes Stage I, maybe I inadvertently omitted some part in the code. It will be great if you could help clarify the implementation structure. Thank you in advance.

**Comment by bertjiazheng** [comment]
Hi, 

Thanks for your interest in our work! The second stage aims to recover the 3D parameter of each planar region. The 3D model mapping step is straight forward, and you can find the implementation by PlaneNet [here](https://github.com/svip-lab/PlanarReconstruction/blob/master/utils/write_ply.py#L33). 

Best,
Jia
