### ISSUE TITLE
How to train on custom dataset?

### ISSUE THREAD

**Issue by kharyal** [svip-lab/PlanarReconstruction#33]
I have some questions about the format of data you are using to train the network.
First of all, I can see that in the `main.py` file you are reading `image`, `plane`, `segmentation`, `depth` from the _.npz_ file.

I assume that `image` and `depth` are the images saved in the .npz file as np arrays.
What is the `plane` that you are reading?
What is the format of `segmentation` in _.npz_ files? Is it RLE, polygons or normal images stored as arrays?

**Comment by bertjiazheng** [comment]
Hi, 

`plane` is the 3D parameter of the plane, which is represented by the plane normal `n` and the plane offset `d`. We store the plane as `plane = n * d`. You can get the plane normal `n = plane / norm(plane)`, and plane distance `d = norm(plane)`. 

`segmentation` is the plane instance segmentation, which is stored as `H x W` array.

I hope this helps to answer your concern.

Best,
Jia

**Comment by bertjiazheng** [comment]
Feel free to re-open this issue if you still have questions.

**Comment by kharyal** [comment]
What is the shape of `planes` (if I have k planes in an image)?

**Comment by bertjiazheng** [comment]
`planes` is a `k x 3` matrix.
