### ISSUE TITLE
about trained model 

### ISSUE THREAD

**Issue by ReeseL** [svip-lab/PlanarReconstruction#37]
Hi, 
Thanks for your work! I have a question about the trained model you provided. Could you please tell me the dataset you used to train ? they are ScanNet or NYUv2 ?
thanks!
best regard
Reese

**Comment by bertjiazheng** [comment]
Hi @ReeseL 

The provided model is pretrained on the ScanNet.

Best,
Jia

**Comment by ReeseL** [comment]
ok, thanks!
