### ISSUE TITLE
About datasets

### ISSUE THREAD

**Issue by RenQJ** [svip-lab/PlanarReconstruction#43]
The link of datasets that planenet provides seems not to work, can you share datasets in other ways with me?

planenet作者提供的数据集链接已经失效，您可以通过其他方式把数据集分享给我吗？我的邮箱是renqjhit@163.com。

**Comment by lijing1996** [comment]
> The link of datasets that planenet provides seems not to work, can you share datasets in other ways with me?
> 
> planenet作者提供的数据集链接已经失效，您可以通过其他方式把数据集分享给我吗？我的邮箱是[renqjhit@163.com](mailto:renqjhit@163.com)。

I'm the friend of Zehao and I'm zipping the dataset now. I will drop to you ASAP.

**Comment by bertjiazheng** [comment]
Hi @RenQJ

I am sorry we could not distribute the data due to the copyright issue. Please contact the authors of PlaneNet.

Best,
Jia

**Comment by EryiXie** [comment]
The author of PlaneRCNN, as well as PlaneNet, provide the dataset annotation here:
https://www.dropbox.com/s/u2wl4ji700u4shq/ScanNet_planes.zip?dl=0

**Comment by RenQJ** [comment]
| |
King吉
|
|
***@***.***
|
签名由网易邮箱大师定制
Sorry to ignore the email. I have downloaded the dataset. Thank you anyway and looking forward to further communication.
On 11/8/2021 16:46，Jing ***@***.***> wrote：

The link of datasets that planenet provides seems not to work, can you share datasets in other ways with me?

***@***.***。

I'm the friend of Zehao and I'm zipping the dataset now. I will drop to you ASAP.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by ArcherFMY** [comment]
@RenQJ Hi, I meet the same problem when downloading the datasets. Have you got the datasets?
