### ISSUE TITLE
How can I get a 3D model?

### ISSUE THREAD

**Issue by XGuider** [svip-lab/PlanarReconstruction#6]
Hi author,

thanks for your impressive work.

 After I run the following command,

 python predict.py eval with resume_dir=pretrained.pt input_image=/path/to/image 

 How can I get a 3D model after getting the results?

Many Thanks.

**Comment by bertjiazheng** [comment]
Please refer to [write_ply.py](https://github.com/svip-lab/PlanarReconstruction/blob/35651a8e84fc3be632dbaf5b1c6a317a28a59aac/utils/write_ply.py#L31).

**Comment by XGuider** [comment]
Bert Jia Zheng


Thank you very much for answering my question and thank you very much for your work. 


 I am a Chinese student, so I want to explain my question more clearly in Chinese.


“师兄，您好。我想问的是我通过您的工作得到平面掩码和深度图，怎样得到3D图像？
（是通过meshlab软件得到的吗？）
”
“同时，阅读某些基础后，感觉知识体系建立不好。希望师兄能推荐下学习3D重建的学习步骤和资料推荐”
“非常感谢！打扰师兄了，再此先谢过师兄！”




------------------ 原始邮件 ------------------
发件人: "Bert Jia Zheng"<notifications@github.com>;
发送时间: 2019年4月18日(星期四) 晚上6:05
收件人: "svip-lab/PlanarReconstruction"<PlanarReconstruction@noreply.github.com>;
抄送: "Xslience"<973279990@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [svip-lab/PlanarReconstruction] How can I get a 3D model? (#6)




Closed #6.

**Comment by bertjiazheng** [comment]
1. run [write_ply](https://github.com/svip-lab/PlanarReconstruction/blob/35651a8e84fc3be632dbaf5b1c6a317a28a59aac/utils/write_ply.py#L31) to get the point cloud.
2. visualize the reconstructed model by loading into the Meshlab.

**Comment by XGuider** [comment]
Many thanks!


 
---Original---
