### ISSUE TITLE
want to use pretrained.pt

### ISSUE THREAD

**Issue by 411066282** [svip-lab/PlanarReconstruction#7]
how to handle this error:
/home/yao/.torch/models/resnet101-imagenet.pth
when type "python predict.py eval with resume_dir=/pretrained.pt input_image=/image"

**Comment by niujinshuchong** [comment]
@411066282 The default config will load a pretrained imagenet model, it can be disabled simply by
python predict.py eval with model.pretrained=False resume_dir=/pretrained.pt input_image=/image
