### ISSUE TITLE
data conversion

### ISSUE THREAD

**Issue by glacierwl** [svip-lab/PlanarReconstruction#9]
when i am converting the .tfrecords to .npz, something wrong happened.    Error:  " out of range error, FIFOQueue '_1_batch/fifo_queue' is closed and has insufficient elements'  " What can i do to solve the problem?thank you

**Comment by niujinshuchong** [comment]
@glacierwl We set a big number as the sample size since at the begining we don't know the size of the .tfrecords. When the error happens, it means the conversion is completed.

**Comment by jcliu0428** [comment]
@glacierwl Hi,I guess you have not completed the file name.
Use --input_tfrecords_file = planes_scannet_train.tfrecords instead of ----input_tfrecords_file=*train.tfrecords and the problem should be settled.
